### ISSUE TITLE
deploy pouchdb-server to Heroku

### ISSUE THREAD

**Issue by vdclouis** [pouchdb/pouchdb-server#124]
Hi, I'm not sure this is the best place for this, so feel free to close this and point me in the right direction :)

I'm kinda stuck trying to run pouchdb-server on Heroku.
The logs say pouchdb-server is running: `[info] pouchdb-server has started on http://127.0.0.1:5984/`
But I bet I miss some configuration as my Heroku app just times out when trying to navigate to it.

Any help is super welcome!

**Comment by marten-de-vries** [comment]
I've got no experience with heroku, but did you try listening at 0.0.0.0 instead of 127.0.0.1? I can imagine that's required to expose it. Otherwise, no idea if there's nothing else in the logs. This can be changed in config.json or using the --host CLI option.

**Comment by nolanlawson** [comment]
Some hosting providers are finicky about ports. You may want to try port 9000 instead.

**Comment by bkniffler** [comment]
You don't get to choose your own port at heroku, you need to use `process.env.port` as heroku will assign a specific port to your app and hand it over with that environment variable.

**Comment by seigel** [comment]
@vdclouis If you are still working on this here is a procfile excerpt that might be usefule for you:

`web: node ./bin/pouchdb-server -p $PORT -o 0.0.0.0`

Note that when the server restarts, i.e. when dynos get recycled at certain times of the day that the databases will go missing and your admin password, if you set one, will be gone as well.

You can overcome the admin password problem by adding a `config.json` file to the root of your project  containing an appropriate "admins" section with the password encoded properly.  This will keep an admin password set for your deploy.  However restarts will still wipe out  your databases.  Also since disk storage is ephemoral (sp?) then you aren't guaranteed to be able to store your data on the dis appropriately either.  Take a look at redisdown with the --level-down setting.

`web: node ./bin/pouchdb-server -p $PORT -o 0.0.0.0 --level-backend redisdown`

This may sound good but will look for redis running on the same host as your server and well, that ain't gunna happen in heroku.  Find the appropriate place in the pouchdb-server file to add the required url setting for redisdown to point to REDIS_URL (assuming you've attached a redis instance to your deploy) and now you should have a db that persists and is admin password controlled.

Something like:

`opts.url=process.env.REDIS_URL`

Cheers

**Comment by nolanlawson** [comment]
this is fixed now that we support PORT. it should be very easy to deploy pouchdb-server to heroku

**Comment by aguynamedben** [comment]
@seigel Thanks for your helpful tip on using `--level-bankend redisdown` to back pouchdb-server with Redis to run it on Heroku.

I have a question about this part:
> Find the appropriate place in the pouchdb-server file to add the required url setting for redisdown to point to REDIS_URL

Would this require me to fork/change the pouchdb-server code or is there a way to pass that as a command line argument? I'm currently running with this command:

```
pouchdb-server --port $POUCHDB_PORT --host $POUCHDB_HOST --config config.json --level-backend redisdown
```

`pouchdb-server --help` says that will try to connect to the Redis server at `localhost:6379`, but I'm wondering how to get it to respect Heroku's `REDIS_URL` without making a fork.

Any ideas? Thanks for your time.

**Comment by seigel** [comment]
You'd have to fork if they haven't already added that ability.  I can't remember if I made a PR for that or not. :)

Good luck. Reach out again if you have issues 

James

**Comment by seigel** [comment]
The example hack to use this on heroku will be something similar to this.: https://github.com/pouchdb/pouchdb-server/pull/311

**Comment by MerovingianByte** [comment]
I npm installed redisdown but now with the command `--level-backend redisdown` the app won't start. Without that command the app starts normally. Is it maybe because when I install redisdown I get this message?:

> npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.

> + redisdown@0.1.12
> added 4 packages in 12.696s
