### ISSUE TITLE
Pass other args to Leveldown - not just prefix

### ISSUE THREAD

**Issue by kcrkor** [pouchdb/pouchdb-server#142]
The server only passes the prefix option used with riakdown. None of the other standard options are supported most importantly host and port.

**Comment by nolanlawson** [comment]
This is something I would prefer not to support, since we can't anticipate every option that every *down adapter might want to use. However we ought to have some way for users to be able to call a JavaScript file that contains a function that returns a `*down` configuration. Or something. I dunno. You could also just fork pouchdb-server.

**Comment by kcrkor** [comment]
I have cloned it for now, but I think that would really increase the versatility of the server. When it comes to having it containerised and easily used with other backends through leveldown the whole thing could be a pretty handy. Currently it misbehaves when a volume is used as data dir and needs a wrapper to catch signals, both of which are solved by using a different db backend.

**Comment by nolanlawson** [comment]
Can you explain that bug a little further? I've never heard of it before. Does it happen with both LevelDB and SQLite or only LevelDB? Perhaps it should be filed as a separate issue.

**Comment by nolanlawson** [comment]
Currently out of scope; folks are free to copy-paste the pouchdb-server source code and use express-pouchdb however they wish; that is kind of the goal of express-pouchdb
