### ISSUE TITLE
RFC: Combine Pouchdb-server and express-pouchdb

### ISSUE THREAD

**Issue by garrensmith** [pouchdb/pouchdb-server#150]
I would like to combine pouchdb-server and express-pouchdb into one git repo and one npm module. At the moment maintaining them is quite difficult. The biggest issue we have when developing on pouchdb-server and express-pouchdb is testing them. It gets convoluted as they both require each other before you can test them against a release of pouchdb.

Originally I tried to do this in the monorepo, but I think that is probably more ambitious than what is needed here. And since we still testing out the monorepo idea with pouchdb, I would prefer to wait a bit until we know exactly how to manage a monorepo before moving pouchdb-server in that direction. But I would still like to have pouchdb-server and express-pouchdb in a more workable state. And later if needed we can move to a monorepo with the other packages that pouchdb-server and express-pouchdb use.

The api would look something like this when using `express-pouchdb`

```
var express = require('express'),
    app     = express(),
    PouchDB = require('pouchdb');

app.use('/db', require(pouchdb-server')(PouchDB));

app.listen(3000);
```

And then it would stay the same for when using pouchdb-server

`$ pouchdb-server -p 5984`

Looking for feedback from anyone interested but especially @nolanlawson @daleharvey @marten-de-vries @yaronyg  and @robertkowalski

**Comment by daleharvey** [comment]
So I have less skin in the game due to maintaining `pouchdb-express-router` which serves my needs so not hugely fussed what happens here, however to give some background, the reason for `pouchdb-server` and `express-pouchdb` to be seperate modules is to serve 2 sets of users. 

`express-pouchdb` was for users building expressjs web applications that wanted to mount a couchdb compatible http end point within their application. It does not have a dependency on `pouchdb` because the developer is supposed to being along their own version of PouchDB, which they may have configured, set up defaults, and have direct / local access etc.

`pouchdb-server` was built to be a minimal consumer of `express-pouchdb` for users that wanted a standalone CouchDB server but using PouchDB, they could easily install it and interact with it via HTTP, (it has the `pouchdb` dependency

if the `pouchdb` dep is `*` then it will (may?) be dedupped with the users own pouchdb dep, so as long as they still pass their version in it may be the extra dep doesnt have a downside (not totally certain about how npm dedupes, may wanna check this)

**Comment by robertkowalski** [comment]
I'm curious if the overhead for the modularity is worth it. 

Not sure why people would want to mount database endpoints within their application - do we know projects that have this use case?

**Comment by daleharvey** [comment]
I do it within every application I write and think its by far the best way to do things, but also worth mentioning that `pouchdb-express-router` now fills in this functionality very will (imo) so that may mean less of a requirement for `pouchdb-server` to do so

**Comment by yaronyg** [comment]
Again, for whatever it's worth, we took a very similar approach in Thali to the express-pouchdb/pouchdb-server divide. Thali's production code which is 100% dependent on both PouchDB and Express-PouchDB doesn't actually list either project in our package.json. We expect the developer to bring their own. The reason for this is that we run in lots of fun places. On phones we run on JXcore. On embedded systems and desktops we can sometimes run on JXcore and sometimes not. We also want to actively experiment with different kinds of backends for PouchDB. The bottom line is that we really value the flexibility.

And ideally we would want to have the same flexibility in express-pouchdb. That is, to bring our own pouchdb with express-pouchdb.

But this approach defeats the whole purpose of pouchdb-server which is just to be a 'batteries included' approach and really should include a specific version of PouchDB.

If we combined the two together I think the only real damage would be that projects like ours that are space sensitive would need to delete the version that was automatically included with pouchdb-server. Which isn't the end of the world.

To me however the more interesting question is - for a project like Thali's why can't we use pouchdb-express-router? I haven't had time to do a deep dive but one of the first things that came up was that it looks like pouchdb-express-router doesn't support bulk_get.

**Comment by nolanlawson** [comment]
I'm fine with combining the two. Right now pouchdb-server is basically just a binary executable on top of express-pouchdb. Would be fine with deprecating express-pouchdb entirely.

**Comment by garrensmith** [comment]
@daleharvey has a point around the `dedupe`. It could be an issue. Reading the [npm docs](https://docs.npmjs.com/how-npm-works/npm3-dupe) I think in most cases it would be fine. But in some cases it could cause an issue.

The easiest solution then is to keep them separate, but then make it that express-pouchdb doesn't depend on pouchdb-server for testing. We can do something similar to the minimal test setup in express-pouchdb but make another one that uses all the modules and then test against pouchdb. Would that work better?

**Comment by nolanlawson** [comment]
done in #168!
