### ISSUE TITLE
version 4.0: High severity security issue due to outdated dependency

### ISSUE THREAD

**Issue by seriousme** [pouchdb/pouchdb-server#297]
Regular Expression Denial of Service (ReDoS)
Vulnerable module: fresh
Introduced through: serve-favicon@2.3.2
Detailed paths
Introduced through: pouchdb-server@4.0.0 › serve-favicon@2.3.2 › fresh@0.3.0 
Remediation: Upgrade to serve-favicon@2.4.5.

https://snyk.io/test/npm/pouchdb-server?severity=high&severity=medium&severity=low

Seems easy to fix :-)

**Comment by marten-de-vries** [comment]
Thanks for your bug report!

I just tried to fix it by re-enabling Greenkeeper, which would solve the underlying problem of us not noticing old versions as well. It disabled some time in the past for this repository because of a lack of tests. It seems it's not possible to reset the repository without taking Greenkeeper down over the whole pouchdb organization, so I've mailed Greenkeeper support. Waiting for that now.

**Comment by seriousme** [comment]
Great to see you are working on a structural fix!
In the mean time, can we already fix this by just upgrading to serve-favicon@2.4.5 ?

Greenkeeper will autoclose any branches you already fixed yourself ;-)

**Comment by marten-de-vries** [comment]
4912ec9

**Comment by seriousme** [comment]
Great to see its fixed, but will there be a version 4.0.1 or something similar on NPM ?
