### ISSUE TITLE
Do not create log files

### ISSUE THREAD

**Issue by denis-sokolov** [pouchdb/pouchdb-server#98]
Any run of `pouchdb-server` creates `log.txt`.
It would be really nice if that would be created only if asked (`--log=log.txt`, for example), and not by default, throwing crap in my directory. At the very least I'd like an option to silence it (`--no-log`).
Opinions?

**Comment by marten-de-vries** [comment]
There are a few options to currently disable logging. The first one is to setup express-pouchdb with a custom mode which excludes 'logging-infrastructure'. See for more information https://github.com/pouchdb/express-pouchdb#example-2 . That does take down a few things depending on logging functionality down with it, though.

The nicer option is to change the /_config/log/file option to /dev/null. This does require a config.json file though, which you don't want either.

In the end, the config and log file are just as vital to pouchdb-server as they are to couchdb: both can't do without. If them littering your directory is the only problem, why not just place them, say, with the db files or in a temporary directory? the ``--config`` option combined with the configuration option above definitely helps with that.

**Comment by denis-sokolov** [comment]
I can throw them into `/tmp` or wherever, and I can generate random paths for them to prevent collisions, but that's a lot of extra bother. Anyone running `pouchdb-server` for automated testing or development purposes hardly needs logfiles by default and needs to workaround this issue.

In addition, I feel a general feeling of wronginess that an app by default spams in the current directory. 
Consider the [Rule of Silence](http://www.faqs.org/docs/artu/ch01s06.html#id2873540) of Unix philosophy. Consider the case of `npm-debug.log` file. Even though that only shows up in case of a problem, it has still made many people [feel negative about it](https://github.com/npm/npm/issues/1548).

Feel free to make any decision and close this topic if you are not interested in changing the behavior.
I just wanted to know whether I should workaround or maybe perhaps my workaround will be unnecessary. :)

**Comment by marten-de-vries** [comment]
I don't like using the cwd for log files either, but for npm-installed scripts a /var/log/pouchdb-server.log default is not really an option.

---

Currently the whole logging mechanism works like this:
- express-pouchdb writes log info to log files, depending on ``/_config/log/file`` and ``/_config/log/level``.
- pouchdb-server reads the value of ``/_config/log/file``, and starts watching it, pretty printing any new log lines to stdout.

I don't really want to make /dev/null the default, because that would stop the stdout log info too. If instead of relying on tailing a file pouchdb-server would use some express-pouchdb API, that would become possible without any real downsides, though. I wouldn't be opposed to merging such a workaround.

**Comment by denis-sokolov** [comment]
Ah, I'm afraid this is getting too big for the benefit. I don't think I'll be able to help with this. Thank you for your feedback.

**Comment by denis-sokolov** [comment]
For future reference: `minimumForPouchDB` mode in [express-pouchdb](https://github.com/pouchdb/express-pouchdb) disables all files in my experience at the moment.

**Comment by nolanlawson** [comment]
I believe this is fixable using configuration options now, if not please reopen
